# fly.toml — OpenWebUI developer build (public image tag)

app = "openwebui-devbuildnew"
primary_region = "ord"

[build]
  image = "ghcr.io/open-webui/open-webui:dev"   # public, no auth needed

[[mounts]]
  source       = "openwebui_data"
  destination  = "/app/backend/data"
  initial_size = "1gb"

[http_service]
  internal_port        = 8080
  force_https          = true
  auto_stop_machines   = true   # shut down when idle
  auto_start_machines  = true
  min_machines_running = 0
  processes            = ["app"]
