# fly.toml — Open WebUI (developer build) on Fly.io

app = "openwebuidevbuild"
primary_region = "ord"

[build]
  image = "ghcr.io/open-webui/open-webui-dev:latest"

[env]

[[mounts]]
  source       = "openwebui_data"
  destination  = "/app/backend/data"
  initial_size = "1gb"

[http_service]
  internal_port        = 8080
  force_https          = true
  auto_stop_machines   = true
  auto_start_machines  = true
  min_machines_running = 0
  processes            = ["app"]
