# fly.toml — OpenWebUI developer build, using a pre-built container image

app = "openwebui-devbuildnew"
primary_region = "ord"

[build]
  image = "ghcr.io/open-webui/open-webui-dev:latest"   # pulls the ready-made dev image

[[mounts]]
  source       = "openwebui_data"
  destination  = "/app/backend/data"
  initial_size = "1gb"

[http_service]
  internal_port        = 8080
  force_https          = true
  auto_stop_machines   = "stop"   # shut down when idle; you’re billed only for the 1 GB volume
  auto_start_machines  = true
  min_machines_running = 0
  processes            = ["app"]
